/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codechallenges.linkedList;

import codechallenges.linkedList.LinkedList;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LinkedListTest {
    @Test
    void testLinkedListInsertion(){
        LinkedList sut = new LinkedList();
        sut.append(8);
        sut.append(9);
        assertThrows(IllegalArgumentException.class, () -> sut.insertBefore(10, 8));
    }
}